# Generated by Django 4.1.7 on 2023-03-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postted_by',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
